name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Serveur Personelle
    env:
      SKIP_EXTERNAL_TESTS: "true"    # set this in CI only
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo05_db" >> .env
          echo "DB_USER=labo05" >> .env
          echo "DB_PASS=labo05" >> .env
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Creer labo05-network
        run: docker network create labo05-network

      - name: Demarer les containers
        run: |
          docker compose up -d

      - name: Attendre que MySQL soit prêt
        run: |
          for i in {1..5}; do
            if mysqladmin ping -h localhost -ulabo02 -plabo02 --silent; then
              break
            fi
            sleep 5
          done 

      - name: Run tests
        working-directory: src
        run: python -m pytest

      - name: Deploy Store Manager + Payment Service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}     
          username: ${{ secrets.SERVER_USER }}  
          key: ${{ secrets.SERVER_SSH_KEY }}     
          script: |
            cd ~/ETS/LOG430/LAB5
            ./deploy-payment.sh
            ./deploy.sh